
[window]
dimensions = { columns = 175, lines = 60 }
decorations = "transparent"
blur = true
padding = { x = 4, y = 0 }
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[general]
import = ["~/.config/alacritty/themes/kanagawa_dragon.toml"]
