[window]
dimensions = { columns = 175, lines = 60 }
decorations = "transparent"
opacity = 0.92
blur = true
padding = { x = 8, y = 32 }

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 15
